version: '3.0'

networks:
  gin:
    external: true

services:
  my-gin:
    image: my-gin:v0.0.1
    container_name: my-gin
    build:
      context: . # build路径上下文
      dockerfile: ./Dockerfile # 使用的dockerfile文件作为构建模板
    restart: always
#    command: sh -c "sleep 600 && ./main" # 先sleep 600秒，再执行main
    command: ./main
    privileged: true
    ports:
      - "18888:28888"
    networks:
      - gin